swagger: '2.0'
info:
  title: AssetsProcessing
  description: Контракт для получения дельт актива, а так же для управления паспортом, метриками и групами уязвимостей актива.
  version: "1.1.0"
schemes:
  - http
produces:
  - application/json
paths:
  /api/assets:
    get:
      operationId: GetAssetInfos
      parameters:
        - name: assetIds
          in: query
          required: false
          type: array
          items:
            type: string
            format: uuid
        - name: presence
          in: query
          required: false
          default: all
          schema:
            $ref : '#/definitions/AssetPresenceFilter'
      responses:
        204:
          description: NoContent
        400:
          description: BadRequest
        200:
          description: OK
          schema:
            type: array
            items:
              $ref : '#/definitions/AssetInfoDto'
  /api/assets/by_type:
    get:
      operationId: GetAssetInfosByType
      parameters:
        - name: types
          in: query
          required: false
          type: array
          items:
            type: string
        - name: presence
          in: query
          required: false
          default: all
          schema:
            $ref : '#/definitions/AssetPresenceFilter'
      responses:
        204:
          description: NoContent
        400:
          description: BadRequest
        200:
          description: OK
          schema:
            type: array
            items:
              $ref : '#/definitions/AssetShortInfoDto'

  /api/assets/{assetId}/raw:
    get:
      operationId: GetAssetRawData
      parameters:
        - name: assetId
          in: path
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: OK
          schema:
            type: string
            format: raw

  /api/assets/{assetId}/raw/stream:
    get:
      operationId: GetAssetRawDataStream
      parameters:
        - name: assetId
          in: path
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: OK
          schema:
            type: string
            format: binary
        400:
          description: Ошибка запуска операции
          x-errors:
            - $ref: '#/definitions/AssetNotFoundError'

  /api/assets/{assetId}/raw/{checkpoint}:
    get:
      operationId: GetAssetRawDataByCheckpoint
      parameters:
        - name: assetId
          in: path
          required: true
          type: string
          format: uuid
        - name: checkpoint
          in: path
          required: true
          type: integer
          format: int64
        - name: includeRemoved
          in: query
          required: false
          type: boolean
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/SnapshotDto'
        400:
          description: Ошибка запуска операции
          x-errors:
            - $ref: '#/definitions/AssetNotFoundError'

  /api/assets/{assetId}/raw/{checkpoint}/stream:
    get:
      operationId: GetAssetRawDataStreamByCheckpoint
      parameters:
        - name: assetId
          in: path
          required: true
          type: string
          format: uuid
        - name: checkpoint
          in: path
          required: true
          type: integer
          format: int64
        - name: includeRemoved
          in: query
          required: false
          type: boolean
      responses:
        200:
          description: stream
          schema:
            type: string
            format: binary
        400:
          description: Ошибка запуска операции
          x-errors:
            - $ref: '#/definitions/AssetNotFoundError'

  /api/assetPassport/{assetId}/effectiveMetric:
    post:
      operationId: GetPreviewEffectiveMetric
      parameters:
        - type: string
          name: assetId
          in: path
          required: true
          format: guid
        - name: metricsDto
          in: body
          schema:
            $ref: '#/definitions/AssetMetrics'
          required: true
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/AssetMetricsDto'
        404:
          description: ''
          schema:
            $ref: '#/definitions/ErrorDescriptor'
definitions:
  AssetPresenceFilter:
    type: string
    description: Фильтр по активам
    enum:
      - all
      - alive
      - closed
  ErrorDescriptor:
    type: object
    properties:
      error:
        $ref: '#/definitions/ErrorDescriptorErrors'
    description: Описание ошибки
  ErrorDescriptorErrors:
    type: object
    required:
      - code
    properties:
      errors:
        description: Ошибки
        type: array
        items:
          $ref: '#/definitions/ErrorDescriptorItem'
      message:
        type: string
        description: Общее сообщение
      code:
        type: integer
        description: Код ошибки HTTP
        format: int32
    description: Список ошибок
  ErrorDescriptorItem:
    type: object
    properties:
      id:
        type: string
        description: Код ошибки
      sourceName:
        type: string
        description: >-
          Имя подсистемы (сервиса, микросервиса, сайта) в которой произошла
          ошибка
      networkAddress:
        type: string
        description: Сетевые адреса сервиса в котором произошла ошибка
      type:
        type: string
        description: Тип ошибки (шаблона)
      parameters:
        type: object
        additionalProperties:
          type: string
        description: Произвольные параметры ошибки (для вывода в шаблоне)
    description: 'Описание ошибки подсистемы (сервиса, микросервиса, сайта)'
  AssetMetricsDto:
    type: object
    properties:
      metrics:
        type: array
        items:
          $ref: '#/definitions/MetricInputDto'
    required:
      - metrics
  SnapshotDto:
    type: object
    properties:
      content:
        type: string
      revision:
        type: integer
        format: int32
    required:
      - content
      - revision

  AssetMetrics:
    type: object
    properties:
      metrics:
        type: array
        items:
          $ref: '#/definitions/MetricInputDto'
    required:
      - metrics

  AssetInfoDto:
    type: object
    properties:
      id:
        type: string
        format: uuid
      typeName:
        type: string
      scopeId:
        type: string
        format: uuid
      displayName:
        type: string
      version:
        type: integer
        format: int32
      ipAddress:
        type: string
      fqdn:
        type: string
      integralCvssScore:
        type: number
        format: decimal
      vulnerabilityLevel:
        type: integer
      created:
        type: string
        format: date-time
      updated:
        type: string
        format: date-time
      expiration:
        type: string
        format: date-time
      closed:
        type: boolean
      closeReason:
        type: string
        enum:
          - united
          - removedByUser
          - expired
    required:
      - id
      - typeName
      - scopeId
      - displayName
      - version
      - integralCvssScore
      - vulnerabilityLevel
      - created
      - updated
      - closed
  AssetShortInfoDto:
    type: object
    properties:
      id:
        type: string
        format: uuid
      name:
        type: string
    required:
      - id
      - name
  MetricInputDto:
    type: object
    properties:
      type:
        type: string
      id:
        type: string
    required:
      - type
      - id
  
  AssetNotFoundError:
    description: Операция не найдена
    x-discriminator: core.assetNotFound.error
    allOf:
      - $ref: './errors.json#/definitions/Error'
      - type: object